# Generated by Django 4.0.4 on 2022-05-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coles',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
