# Generated by Django 4.0.4 on 2022-05-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coles', '0003_remove_coles_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coles',
            name='is_available',
        ),
    ]
