# Generated by Django 4.0.4 on 2022-05-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coles', '0004_remove_coles_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='coles',
            name='is_last_sync_success',
            field=models.BooleanField(default=False),
        ),
    ]
